// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'jquery', 'backbone', 'models/Committee', 'models/MRFQuestionModule'], function(_, $, Backbone, Committee, MRFQuestion) {
    var MRFQuestionCommitteeDetailView;
    return MRFQuestionCommitteeDetailView = Backbone.View.extend({
      template: _.template('<p> Some stuff </p>'),
      initialize: function() {
        return $.ajax({
          type: 'get',
          url: '_api/'
        });
      }
    });
  });

}).call(this);
