// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'jquery', 'backbone'], function(_, $, Backbone) {
    var TestView;
    TestView = Backbone.View.extend({
      initialize: function() {
        return console.log("Initialized!");
      }
    });
    return TestView;
  });

}).call(this);
