// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'jquery', 'backbone'], function(_, $, Backbone) {
    var Member;
    Member = Backbone.Model.extend({
      urlRoot: '_api/members',
      defaults: {
        unq: void 0,
        first_name: void 0,
        last_name: void 0
      },
      fullName: function() {
        return this.get('first_name') + this.get('last_name');
      },
      validate: function(attrs, options) {
        var errors;
        errors = [];
        if (attrs.name === '') {
          errors.push({
            name: 'unq',
            errorMessage: 'Uniquename cannot be empty. '
          });
        }
        if (attrs.first_name === '') {
          errors.push({
            name: 'first_name',
            errorMessage: 'First name cannot be blank'
          });
        }
        if (attrs.last_name === '') {
          errors.push({
            name: 'last_name',
            errorMessage: 'Last name cannot be blank'
          });
        }
        if (attrs.password === '') {
          errors.push({
            name: 'password',
            errorMessage: 'Password cannot be blank'
          });
        }
        if (attrs.password_confirm === '') {
          errors.push({
            name: 'password_confirm',
            errorMessage: 'Password confirmation cannot be blank'
          });
        }
        if (attrs.password !== attrs.password_confirm) {
          errors.push({
            name: 'password_match',
            errorMessage: 'Password and password confirmation do not match'
          });
        }
        if (errors.length > 0) {
          return errors;
        } else {
          return false;
        }
      }
    });
    return Member;
  });

}).call(this);
